import 'dart:convert';
import 'dart:io';

import 'package:pdf_text/pdf_text.dart';
import 'package:pocketledger/core/models/parsed_transaction_draft.dart';
import 'package:pocketledger/parsers/csv_parser.dart';

class PDFParser {
  final CSVParser _csvParser = CSVParser();

  Future<List<ParsedTransactionDraft>> parse(
    String filePath, {
    String currency = 'INR',
    String? password,
  }) async {
    try {
      final text = await _extractText(filePath, password: password);
      if (text.isEmpty) return [];

      final cleanedLines = _cleanPdfText(text);
      final csvContent = _linesToCsv(cleanedLines);
      final drafts = _csvParser.parse(csvContent, currency: currency);

      return drafts.map((d) {
        final confidence = d.confidence * 0.85;
        return ParsedTransactionDraft(
          date: d.date,
          description: d.description,
          debit: d.debit,
          credit: d.credit,
          amount: d.amount,
          balance: d.balance,
          confidence: confidence,
          rawDescription: d.rawDescription,
        );
      }).toList();
    } on PdfPasswordRequiredException {
      rethrow;
    } catch (e) {
      return [];
    }
  }

  Future<String> _extractText(String filePath, {String? password}) async {
    final normalizedPassword = password?.trim();
    if (await isPasswordProtected(filePath) &&
        (normalizedPassword == null || normalizedPassword.isEmpty)) {
      throw const PdfPasswordRequiredException();
    }

    try {
      final pdfText = await PdfTextExtractor.extractText(
        filePath,
        password: normalizedPassword,
      );
      return pdfText;
    } catch (e) {
      if (_isPasswordError(e.toString())) {
        throw const PdfPasswordRequiredException();
      }
      rethrow;
    }
  }

  static Future<bool> isPasswordProtected(String filePath) async {
    final file = File(filePath);
    if (!await file.exists()) return false;

    final bytes = await file.readAsBytes();
    final headerWindow = bytes.take(4096).toList();
    final allText = latin1.decode(bytes, allowInvalid: true);
    final headerText = latin1.decode(headerWindow, allowInvalid: true);

    return allText.contains('/Encrypt') ||
        headerText.contains('/Encrypt') ||
        headerText.contains('EncryptMetadata');
  }

  bool _isPasswordError(String message) {
    final lower = message.toLowerCase();
    return lower.contains('password') ||
        lower.contains('encrypted') ||
        lower.contains('incorrect password');
  }

  List<String> _cleanPdfText(String text) {
    final lines = text
        .split('\n')
        .map((l) => l.trim())
        .where((l) => l.isNotEmpty)
        .toList();
    final List<String> cleaned = [];

    for (final line in lines) {
      if (_isHeaderOrFooter(line)) continue;
      if (_isPageNumber(line)) continue;

      final merged = _mergeSplitAmounts(line);
      cleaned.add(merged);
    }

    return cleaned;
  }

  bool _isHeaderOrFooter(String line) {
    final lower = line.toLowerCase();
    return lower.contains('statement') ||
        lower.contains('page') ||
        lower.contains('account summary') ||
        lower.contains('generated by') ||
        lower.contains('customer care') ||
        lower.contains('toll free') ||
        lower.contains('email') ||
        lower.contains('branch') ||
        lower.contains('address') ||
        lower.contains('statement from') ||
        lower.contains('statement period') ||
        lower.contains('opening balance') ||
        lower.contains('closing balance');
  }

  bool _isPageNumber(String line) {
    return RegExp(r'^Page\s+\d+\s*(of\s+\d+)?$', caseSensitive: false)
            .hasMatch(line) ||
        RegExp(r'^\d+\s*/\s*\d+$').hasMatch(line);
  }

  String _mergeSplitAmounts(String line) {
    return line.replaceAllMapped(
        RegExp(r'(\d)\s(\d{3})'), (m) => '${m.group(1)}${m.group(2)}');
  }

  String _linesToCsv(List<String> lines) {
    final buffer = StringBuffer();
    final headers = _detectHeaders(lines);
    if (headers != null) {
      buffer.writeln(headers.join(','));
    } else {
      buffer.writeln('Date,Description,Debit,Credit,Balance');
    }

    int startIdx = 0;
    if (headers != null) {
      final headerLine = lines.indexWhere((l) {
        final lower = l.toLowerCase();
        return headers.every((h) => lower.contains(h.toLowerCase()));
      });
      if (headerLine >= 0) startIdx = headerLine + 1;
    }

    for (int i = startIdx; i < lines.length; i++) {
      final processed = _lineToCsvRow(lines[i]);
      if (processed != null) {
        buffer.writeln(processed);
      }
    }

    return buffer.toString();
  }

  List<String>? _detectHeaders(List<String> lines) {
    final headerKeywords = [
      'date',
      'narration',
      'description',
      'particulars',
      'debit',
      'credit',
      'withdrawal',
      'deposit',
      'balance',
      'amount'
    ];
    for (final line in lines) {
      final lower = line.toLowerCase();
      final matches = headerKeywords.where((k) => lower.contains(k)).length;
      if (matches >= 3) {
        return line.split(RegExp(r'\s{2,}')).map((s) => s.trim()).toList();
      }
    }
    return null;
  }

  String? _lineToCsvRow(String line) {
    final parts = line.split(RegExp(r'\s{2,}')).map((s) => s.trim()).toList();
    if (parts.length < 3) return null;

    bool hasDate = false;
    for (final part in parts) {
      if (RegExp(r'^\d{1,2}[/-]\d{1,2}[/-]\d{2,4}$').hasMatch(part)) {
        hasDate = true;
        break;
      }
    }
    if (!hasDate) return null;

    final escapedParts = parts.map((p) {
      if (p.contains(',') || p.contains('"')) {
        return '"${p.replaceAll('"', '""')}"';
      }
      return p;
    }).join(',');

    return escapedParts;
  }
}

class PdfPasswordRequiredException implements Exception {
  const PdfPasswordRequiredException();

  @override
  String toString() => 'PDF password required';
}

class PdfTextExtractor {
  static Future<String> extractText(String filePath, {String? password}) async {
    try {
      final file = File(filePath);
      if (!await file.exists()) return '';

      try {
        final doc = await PDFDoc.fromFile(file, password: password ?? '');
        return await doc.text;
      } catch (_) {
        final data = await file.readAsBytes();
        if (_looksEncrypted(data)) rethrow;
        return _parsePdf(data);
      }
    } catch (e) {
      rethrow;
    }
  }

  static bool _looksEncrypted(List<int> data) {
    final text = latin1.decode(data, allowInvalid: true);
    return text.contains('/Encrypt') || text.contains('EncryptMetadata');
  }

  static Future<String> _parsePdf(List<int> data) async {
    String text = '';
    int pos = 0;

    while (pos < data.length) {
      final streamStart = _indexOf(data, 'stream\n'.codeUnits, pos);
      if (streamStart == -1) {
        final altStart = _indexOf(data, 'stream '.codeUnits, pos);
        if (altStart == -1) break;
        pos = altStart;
      } else {
        pos = streamStart;
      }

      final streamEnd = _indexOf(data, 'endstream'.codeUnits, pos + 7);
      if (streamEnd == -1) break;

      final streamData = data.sublist(pos + 7, streamEnd);

      try {
        final decompressed = zlib.decode(streamData);
        text += _extractTextFromPdfContent(utf8.decode(decompressed));
      } catch (_) {
        try {
          text += _extractTextFromPdfContent(utf8.decode(streamData));
        } catch (_) {}
      }

      pos = streamEnd + 9;
    }

    return text;
  }

  static int _indexOf(List<int> data, List<int> pattern, int start) {
    for (int i = start; i <= data.length - pattern.length; i++) {
      bool found = true;
      for (int j = 0; j < pattern.length; j++) {
        if (data[i + j] != pattern[j]) {
          found = false;
          break;
        }
      }
      if (found) return i;
    }
    return -1;
  }

  static String _extractTextFromPdfContent(String content) {
    final buffer = StringBuffer();
    final regex = RegExp(r"\(([^)]*)\)\s*Tj|\[(.*?)\]\s*TJ|\(([^)]*)\)\s*\'");
    for (final match in regex.allMatches(content)) {
      for (int i = 1; i < match.groupCount + 1; i++) {
        final g = match.group(i);
        if (g != null) {
          buffer
              .write(g.replaceAllMapped(RegExp(r'\\(.)'), (m) => m.group(1)!));
        }
      }
      buffer.write('\n');
    }
    return buffer.toString();
  }
}
